export const MENU_ITEMS = [
  {
    label: "Home",
    href: "/",
  },
  {
    label: "Course Filter",
    href: "/course-filter",
  },
  {
    label: "Document",
    href: "/document",
  },
  {
    label: "Server",
    href: "/server",
  },
  {
    label: "Moodle Themes",
    href: "/moodle-themes",
  },
];
export const courses = [
  {
    title: "Let's get started with Scholastica",
    instructor: "Marcin Czaja",
    startDate: "Wednesday, 20 March 2024",
    endDate: "Thursday, 20 March 2031",
    price: "$119",
    category: "category1",
    image: "/images/availableCource1.png",
    profile: "/images/profile1.png",
  },
  {
    title: "Let's get started with Scholastica",
    instructor: "Marcin Czaja",
    startDate: "Wednesday, 20 March 2024",
    endDate: "Thursday, 20 March 2031",
    price: "$119",
    category: "category1",
    image: "/images/availableCource1.png",
    profile: "/images/profile1.png",
  },
  {
    title: "Let's get started with Scholastica",
    instructor: "Marcin Czaja",
    startDate: "Wednesday, 20 March 2024",
    endDate: "Thursday, 20 March 2031",
    price: "$119",
    category: "category1",
    image: "/images/availableCource1.png",
    profile: "/images/profile1.png",
  },
  {
    title: "Let's get started with Scholastica",
    instructor: "Marcin Czaja",
    startDate: "Wednesday, 20 March 2024",
    endDate: "Thursday, 20 March 2031",
    price: "$119",
    category: "category1",
    image: "/images/availableCource1.png",
    profile: "/images/profile1.png",
  },
  {
    title: "Let's get started with Scholastica",
    instructor: "Marcin Czaja",
    startDate: "Wednesday, 20 March 2024",
    endDate: "Thursday, 20 March 2031",
    price: "$119",
    category: "category1",
    image: "/images/availableCource1.png",
    profile: "/images/profile1.png",
  },
  {
    title: "Let's get started with Scholastica",
    instructor: "Marcin Czaja",
    startDate: "Wednesday, 20 March 2024",
    endDate: "Thursday, 20 March 2031",
    price: "$119",
    category: "category1",
    image: "/images/availableCource1.png",
    profile: "/images/profile1.png",
  },
];
